apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat-server
  template:
    metadata:
      labels:
        app: tomcat-server
    spec:
      containers:
        - name: mytomcatcont
          image: vaibhav9096/tomcat-jenkins-server:v1.1
          ports:
            - containerPort: 9090
          env:
            - name: PORT
              value: "9090"
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9090
  selector:
    app: tomcat-server
